apiVersion: apps/v1
kind: Deployment
metadata:
  name: q
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q
  template:
    metadata:
      labels:
        app: q
    spec:
      containers:
      - image: okteto.dev/q:latest
        name: q
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "154cc32b-e99c-4c06-a1bd-b1ddc960f22f"
        - name: Vless_Path
          value: "/l0712"
        - name: Vmess_UUID
          value: "154cc32b-e99c-4c06-a1bd-b1ddc960f22f"
        - name: Vmess_Path
          value: "/m0712"
        - name: Share_Path
          value: "/v2link"
