apiVersion: apps/v1
kind: Deployment
metadata:
  name: w
spec:
  replicas: 1
  selector:
    matchLabels:
      app: w
  template:
    metadata:
      labels:
        app: w
    spec:
      containers:
      - image: okteto.dev/w:latest
        name: w
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b33ccff2-386f-4f1d-8a68-fa33fef3cd3d"
        - name: Vless_Path
          value: "/555"
        - name: Vmess_UUID
          value: "b33ccff2-386f-4f1d-8a68-fa33fef3cd3d"
        - name: Vmess_Path
          value: "/555"
        - name: Share_Path
          value: "/v2link"
